### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by yvesgoeleven** [MessageHandler/BasketLummen#10]
## What is the problem?

Increase engagement by publishing stories about what is happening in the club.

## Discussion and conclusions

* Blog posts should be in a central location.
* Channel integration should be automated

## Plan of attack

- [x] Setup easy to use content engine (markdown based)
- [x] List recent blog posts on homepage
- [x] List blog posts on 'blog' page
- [x] Create blog post detail page
- [x] Allow visitors to comment and ask questions on the blog post (discuss)
- [ ] Automate twitter integration (postponed https://github.com/MessageHandler/BasketLummen/issues/15)
- [ ] Automate facebook integration (postponed https://github.com/MessageHandler/BasketLummen/issues/16)
- [ ] Automate mailing list integration (postponed https://github.com/MessageHandler/BasketLummen/issues/17)
