### ISSUE TITLE
News

### ISSUE THREAD

**Issue by yvesgoeleven** [MessageHandler/BasketLummen#11]
## What is the problem?

The club has a need to spread news to its members and supporters.

## Discussion and conclusions

* Hot news section on existing website is no longer used, news is now spread across different channels (twitter, facebook, mailing list)
* News items should be in a central location.
* Channel integration should be automated

## Plan of attack

- [x] Setup easy to use content engine (markdown based)
- [x] List recent news items on homepage
- [x] List news items on 'news' page
- [x] Create news item detail page
- [x] Allow visitors to comment and ask questions on the news items (discuss)
- [ ] Automate twitter integration (postponed https://github.com/MessageHandler/BasketLummen/issues/15)
- [ ] Automate facebook integration (postponed https://github.com/MessageHandler/BasketLummen/issues/16)
- [ ] Automate mailing list integration (postponed https://github.com/MessageHandler/BasketLummen/issues/17)
